name: sqlite_cookbook
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  get_it: ^7.6.4
  http: ^1.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.1.1
  riverpod: ^2.4.9
  sqflite: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  test: ^1.24.1

flutter:
  uses-material-design: true
